---
- name: "Install NGINX"
  apt:
    name: nginx
    state: present

- name: "Front configuration"
  when: app == "front"
  copy:
    src: templates/nginx-front.conf.j2
    dest: "{{ sites_enabled_path }}/{{ front_config_file }}"

- name: "Back configuration"
  when: app == "back"
  copy:
    src: templates/nginx-back.conf.j2
    dest: "{{ sites_enabled_path }}/{{ back_config_file }}"

- name: "Restart nginx service"
  command: service nginx reload