---
- name: "Install {{ name }}{{ version }}"
  apt:
    name: "{{ name }}{{ version }}"
    state: present

- name: "Install {{ name }}{{ version }}'s dependencies"
  apt:
    name:
      - "{{ name }}{{ version }}-cli"
      - "{{ name }}{{ version }}-fpm"
      - "{{ name }}{{ version }}-mbstring"
      - "{{ name }}{{ version }}-zip"
      - "{{ name }}{{ version }}-mysql"
      - "{{ name }}{{ version }}-gd"
      - "{{ name }}{{ version }}-curl"
      - "{{ name }}{{ version }}-xml"
    state: present